### ISSUE TITLE
Police Ghost-Hawk is Missing a texture.

### ISSUE THREAD

**Issue by imthatguyhere** [EasysAltisLife/Easys-Altis-Life#10]
It's the first one in the helicopter shop at Kavala HQ: 
![First Ghost Hawk in Garage (non camo)](http://i.imgur.com/9TzsDKW.png)

This is what it looks like: 
![Missing Ghost Hawk Body](http://i.imgur.com/TMjp3B6.jpg)

This is what vehicle code it is:
![B_Heli_Transport_01_F](http://i.imgur.com/NPBiG6z.png)
B_Heli_Transport_01_F

This is what the working one is:
![B_Heli_Transport_01_camo_F](http://i.imgur.com/Lxz4mmg.png)
B_Heli_Transport_01_camo_F

It's probably just a missing texture applied to it.

**Comment by DonLuck** [comment]
Try this skin out. you will need both. Photo shop. 

https://www.dropbox.com/sh/90f6s4xa9amdlec/AACH7u5AT5qp9HUEPypoiHDGa?dl=0

**Comment by DonLuck** [comment]
Scratch that, this is easier.  
http://i.imgur.com/rAQ8RuT.jpg  
   http://i.imgur.com/QtLad05.jpg

**Comment by s1k-altisLife** [comment]
thanks don luck , will fix this and add it in tonight. :D
