### ISSUE TITLE
Add All Donator Items and Vehicles to Rebel Shops - **Report Missing Items Please**

### ISSUE THREAD

**Issue by imthatguyhere** [EasysAltisLife/Easys-Altis-Life#11]
All Donator only items and vehicles need to be added to Civilian and Rebel shops.

Some items and vehicles below, more will be added as reported:
- MX SW
- MX M

Donator items and vehicles that need to be available but expensive:
- Kajman Attack Helicopter
- NightStalker Rifle Sight

**Comment by imthatguyhere** [comment]
See cost suggestion at #21

**Comment by s1k-altisLife** [comment]
Fixed
