### ISSUE TITLE
Police Are Unable to Seize Cases and Ground Items

### ISSUE THREAD

**Issue by imthatguyhere** [EasysAltisLife/Easys-Altis-Life#17]
Cops can scroll-wheel gear and items on the ground, but cannot seize cases and y-items on the ground. This means that cars hit them and get destroyed and they can glitch spawns and you are not able to pick them up.

**Comment by s1k-altisLife** [comment]
Attempted to fix, need testing. =)

**Comment by s1k-altisLife** [comment]
need testing. =) Should be fixed
