### ISSUE TITLE
Police Can't See Illegal Items on Players During Search

### ISSUE THREAD

**Issue by imthatguyhere** [EasysAltisLife/Easys-Altis-Life#19]
Police are unable to see illegal items and drugs in player inventories when searching them. Sidearms are showing but I am not sure if weapons in backpacks show at this point in time (this will be big with the upcoming rule update).

**Comment by s1k-altisLife** [comment]
Should be fixed - need testing. There is a chance cops wont find the drugs - just like in real life.
