### ISSUE TITLE
Helicopters and Jets Blow Up on Spawn

### ISSUE THREAD

**Issue by Tiberione** [EasysAltisLife/Easys-Altis-Life#28]
Helicopters and Jets blow up as they are taken out of the garage depending on location and server lag. Happened numerous times and I myself have witnessed it.

**Comment by Tiberione** [comment]
Helicopters blow up as they are taken out of the garage depending on location and server lag. Happened numerous times and I myelf have witnessed it.

**Comment by imthatguyhere** [comment]
## Issue summary:

It seems that most if not all of the Jet and Helicopter Spawns / Shops are slightly in the ground and it damages or blows them up. Kavala Hospital breaks the sling on spawn, and most Jets explode on the pad at the airfield.

# Possible Solution:

Raise spawns slightly off the ground. Helis and jets don't get damaged by falling slightly.

**Comment by trypants** [comment]
fixed

**Comment by trypants** [comment]
fixed

**Comment by s1k-altisLife** [comment]
Fixed
