### ISSUE TITLE
Spawn Health Issue **Needs Corroborators**

### ISSUE THREAD

**Issue by Toastyy** [EasysAltisLife/Easys-Altis-Life#30]
On most occasions when I spawn in as a cop I will be already fatally wounded or as soon as the spawn menu pops up I will already be dead and when I spawn in the respawn timer activates and I cant get revived and I lose all my gear and inventory

**Comment by imthatguyhere** [comment]
Look for corroboration on this issue as I asked cops and it doesn't seem to happen to anyone else.

**Comment by imthatguyhere** [comment]
Looks like this is likely based on what spawn on debug island you get. Anyone else noticing please report.
