### ISSUE TITLE
Channel 7 News Chopper

### ISSUE THREAD

**Issue by imthatguyhere** [EasysAltisLife/Easys-Altis-Life#4]
Suggested by Cyanide:

A channel 7 News themed hummingbird!

**Comment by imthatguyhere** [comment]
CH7 News Chopper: ![Left Side](http://i.imgur.com/8P1jvG7.jpg) and ![Right Side](http://i.imgur.com/SEQCLdb.jpg)

**Comment by NSG-Cyanide** [comment]
These look amazing!  What about using the same color scheme on an SUV or offroad of something to give them a ground vehicle as well?

**Comment by imthatguyhere** [comment]
Box van and offroad themes maybe. I'll think of something.

**Comment by imthatguyhere** [comment]
Working on larger update including wheeled vehicles at #32

**Comment by imthatguyhere** [comment]
See #34
