### ISSUE TITLE
Random death bug in cocaine processing

### ISSUE THREAD

**Issue by WDAndrew** [EasysAltisLife/Easys-Altis-Life#45]
As soon I walked through the door my character died and body disappeared along with about 100k in gear. A medic tried to revive but no luck. Once back to pick up stuff same thing happened the medic was luckily still there and helped me up and I stopped trying to enter the building.

**Comment by s1k-altisLife** [comment]
going to look into this tonight. Haven't heard others with the same issue.
Sometimes if there is a suitcase or something underground it will kill you when you walk/drive over it, maybe someone died there at processing and bugged the doorway out?.

**Comment by imthatguyhere** [comment]
Tested the area and I was unable to reproduce. Likely a briefcase stuck underground that got you.
