### ISSUE TITLE
Kavala Square Parking

### ISSUE THREAD

**Issue by bushcamper** [EasysAltisLife/Easys-Altis-Life#46]

**Comment by bushcamper** [comment]
Hello. I am getting fed up with cops impounding my vehicle in kavala square. I would just take one quick stop to the butcher shop or dispensary and BOOM. Cops are impounding my vehicle because it technically "illegal' to park there. All im really saying is that there should be a physical parking lot where vehicles and park there for just a moment. Maybe there could even be some kind of fee to park there? I dont know. Its just a suggestion. Thanks for reading!

**Comment by imthatguyhere** [comment]
http://imgur.com/a/A4rT0 has a sneakpeak of exactly what you are talking about coming after wipe.

![New Kavala Square from Above Link](http://i.imgur.com/sfUJG7L.jpg)
