### ISSUE TITLE
Firefighters/national gaurd?

### ISSUE THREAD

**Issue by dabuggzz** [EasysAltisLife/Easys-Altis-Life#47]

**Comment by dabuggzz** [comment]
add in the ability to be a firefighter or National Gaurdsman on active duty or something like that, and allow the military to have alot heavier weapon systems and all so if you have a gang issue the police can call in the national gaurd to hunt them and add fire to the server to have firefighters put out?/ fix cars and pull them out of ditches stuff like that i don't know just a thought

**Comment by imthatguyhere** [comment]
The Firefighters is a thing we are looking into. The national guard won't happen, but SWAT is being revamped.

I'm personally working on a towing system to allow players to tow vehicles for $.

**Comment by dabuggzz** [comment]
well what is the swat being revamped to and do you need swat officers? if so im interested and ill apply if i like what they are being revamped to
