### ISSUE TITLE
Storage containers not working

### ISSUE THREAD

**Issue by dabuggzz** [EasysAltisLife/Easys-Altis-Life#48]
The last few servers i have gotten storage containers for my house, every time i log in after the reset and go to my house the containers are gone.... and ive bought 2 from the rebel base and 1 from a regular market, all three have disappeared, any way to fix this or no

**Comment by dabuggzz** [comment]
_Update_ the one I bought from the regular market works but i do not know about the rebel ones

**Comment by imthatguyhere** [comment]
The storage system is being replaced soon.
