### ISSUE TITLE
Faster Holstered Weapon Drawing

### ISSUE THREAD

**Issue by OfficerShrek** [EasysAltisLife/Easys-Altis-Life#54]
As an officer, I've noticed we tend to hold our weapons out as if we're prepared for combat at all times, and for a role-play server, I believe that if weapon drawing was increased significantly faster, Officers patrolling will not need to have their weapons out as often, and the APD would act more realistic. We always have our side arm out because it takes a long time to draw it when we need it, and this kind of hurts the feeling of role-playing. Just a suggestion to improve role playing. We don't see cops in real life holding their pistol out at all times. For them it's holstered and easy to draw. This could also possibly ease any tension some citizens might have around cops.

**Comment by imthatguyhere** [comment]
Press ; on your keyboard to immediately draw your sidearm and f to draw your primary.
