### ISSUE TITLE
realistic bullet effects/ nerf tasers

### ISSUE THREAD

**Issue by Snake01** [EasysAltisLife/Easys-Altis-Life#62]
the fact that cops have tasers than can stun you from 250m is a little OP for them nothing can carry and electric charge that far without being hooked to a battery/when people get hit with a bullet from a rifle @ 2000FPS+ they get knocked down period not a man alive that can take it regardless of armor. you can keep damage the same.

**Comment by imthatguyhere** [comment]
There's a hard limit on the tasers at just short of 20m. So, this is unsubstantiated hatred as far as I can tell.

**Comment by Snake01** [comment]
thats not true a cop from the gate of the PD tased me on the rocks up on the hill

**Comment by imthatguyhere** [comment]
I will get someone to retest tonight to see of that changed and update this
issue.

**Comment by imthatguyhere** [comment]
Tested by Me and APD Officer I.Naumann. The range is 35 meters max for both the taser and the taser rifle. Issue remains closed.

[Video of the testing](https://www.youtube.com/watch?v=MSviaHlGT58)
