### ISSUE TITLE
2 weeks waiting to apply

### ISSUE THREAD

**Issue by RyanFromAltis** [EasysAltisLife/Easys-Altis-Life#64]
Don't you think 2 week waiting to re-apply is a little much for just a video game? When it's only 1 week to apply to be an officer. What if someone (like me for instance) doesn't write down the date they started and feels like it's been roughly about a week and your play time was incorrect because it's not publicly/privately viable? Then you're SOL and now you have to wait 2 weeks on top of the 1 week you thought you've already played.

**Comment by imthatguyhere** [comment]
That's really nothing to do with the issue and suggestion tracker, you would likely have a better response via the forums. As for your query, the decision of time to re-apply is variable and decided by the APD. There's a question on the app asking if you are patient, which clearly you are not.
