### ISSUE TITLE
Servers constantly crashing v

### ISSUE THREAD

**Issue by James2238** [EasysAltisLife/Easys-Altis-Life#73]
I don't know if we are being DDOSED or if there is to much happening but every hour or so the server 1 will crash. please find a fix. even if you have to remove santa droppings.

**Comment by imthatguyhere** [comment]
We've already addressed this in #69 . It's due to the 1.54 arma update. We can rollback or start from scratch for an immediate fix. That would mean no random players or no content, so we will be dealing with these issues until bohemia releases a real fix to that last patch.
