### ISSUE TITLE
Medkits

### ISSUE THREAD

**Issue by Treesx** [EasysAltisLife/Easys-Altis-Life#78]
Ive crafted several medkits only to find out they can't be used by a civ. Not sure whether this was intentionally implemented, although i do say it is kinda lame

**Comment by imthatguyhere** [comment]
Rebels can't revive. There is discussion of a system of allowing rebels with a certain level of experience with first aid to revive, but it won't be everyone. I believe you can heal yourself of the kit, but that may not be the case.
