### ISSUE TITLE
Police lights glitched

### ISSUE THREAD

**Issue by Aviri** [EasysAltisLife/Easys-Altis-Life#83]
Minor glitch, but still there, might be hard to reproduce since I've never seen this happen before. I was in pursuit of a speeder (so I turned my lights on), once I was finished with him, I came back and saw this.

http://i.imgur.com/HEa1tga.jpg

**Comment by Aviri** [comment]
The lights are on the ground and working as they would on a cop vehicle.

**Comment by Aviri** [comment]
I hopped back into my car and shut the lights off, it seems to work with the ones on the ground.

**Comment by Aviri** [comment]
Edit: Reproducable with the hatchback, just turn your lights on and they will be on the floor, not on the car. I suggest trying yourself. Maybe it's just me?

**Comment by imthatguyhere** [comment]
Have not run into this issue yet, but will update if I can reproduce it.
