### ISSUE TITLE
Hunting Bug

### ISSUE THREAD

**Issue by Faliofighter** [EasysAltisLife/Easys-Altis-Life#85]
When you get inventory full or null error while hunting you can't acces the y menu holster your weapon or unlock your vehicles https://www.youtube.com/watch?v=6l6qAZC31Jo

**Comment by imthatguyhere** [comment]
This isn't actually a hunting bug. After 1.56 there is an issue where if an animation doesn't complete properly you get stuck for a while while nothing seems to work. Pressing F8, and double tapping backspace generally fixes it but if not within 5 minutes it generally unlocks.
