### ISSUE TITLE
Gangs

### ISSUE THREAD

**Issue by sdkayy** [EasysAltisLife/Easys-Altis-Life#94]
if you try to create a gang with a name that is already taken it will close the dialog and say that it ran into an error and the name is taken but then you cannot reopen the create gang dialog on the y menu.

**Comment by hillbillfied30** [comment]
glitched into a gang every time i load in and am currently in a different gang

**Comment by imthatguyhere** [comment]
http://forum.a3lrp.com/index.php?/forum/20-help-desk/ Post up a topic there with your playerid and what gang it is.
