### ISSUE TITLE
gang glitch

### ISSUE THREAD

**Issue by hillbillfied30** [EasysAltisLife/Easys-Altis-Life#95]

**Comment by hillbillfied30** [comment]
always in a gang when i spawn in and now longer am in that gang. my gang history needs to be removed if thats possible

**Comment by imthatguyhere** [comment]
I'm currently on LOA but if you want this handled post your playerid and the gang you spawn in on the helpdesk:
http://forum.a3lrp.com/index.php?/forum/20-help-desk/
