### ISSUE TITLE
Gang Glitch

### ISSUE THREAD

**Issue by DillyDill1** [EasysAltisLife/Easys-Altis-Life#96]
my in game name is DillyDill. my gang does not allow me to invite anybody. it says your gang is full when I try to invite. I have also upgraded my gang and it has done nothing. one of the mods has told me that the admin has to manually delete all of my players in the gang or the gang history (something like that) please help I will be on the server tomorrow around 3pm central if you need me to give player ID

**Comment by imthatguyhere** [comment]
http://forum.a3lrp.com/index.php?/forum/20-help-desk/ Post there with your playerid and the gang name.
